import { configureStore ,createSlice } from '@reduxjs/toolkit'

// Explicitly set the state type
type Theme = 'light' | 'dark';

// Create a slice of the store for global state management
const globalSlice = createSlice({
    name: 'global',
    initialState: {
        theme: 'dark' as Theme
    },
    reducers:{
        toggleTheme(state) {
            state.theme = state.theme === 'dark' ? 'light' : 'dark'
        }
    }
})

// Configure the store with the global slice reducer
const store = configureStore({
    reducer: {
        global: globalSlice.reducer
    }
});

// This type represents the entire state of the store, set and forget line
export type RootStateType = ReturnType<typeof store.getState>;

// Export the actions generated by the global slice
export const globalActions = globalSlice.actions;

export default store;